### ISSUE TITLE
created_at undefined

### ISSUE THREAD

**Issue by jsonkcli** [Rishikant181/Rettiwt-API#383]
#347 

This error is occurring today, I can't really tell which line  in my code tho, it's not showing in the stack but but looks like the search method and garrytan username is what I'm experiencing the error with

error TypeError: Cannot read properties of undefined (reading 'created_at')
    at new Tweet (/Users/iandeeq/dev/purpleai/node_modules/rettiwt-api/src/models/Tweet.ts:76:33)
    at new CursoredData (/Users/iandeeq/dev/purpleai/node_modules/rettiwt-api/src/models/CursoredData.ts:34:20)
    at TweetService.FetcherService.extractData (/Users/iandeeq/dev/purpleai/node_modules/rettiwt-api/src/services/FetcherService.ts:185:10)
    at TweetService.<anonymous> (/Users/iandeeq/dev/purpleai/node_modules/rettiwt-api/src/services/FetcherService.ts:207:21)
    at step (/Users/iandeeq/dev/purpleai/node_modules/rettiwt-api/dist/services/FetcherService.js:33:23)
    at Object.next (/Users/iandeeq/dev/purpleai/node_modules/rettiwt-api/dist/services/FetcherService.js:14:53)
    at fulfilled (/Users/iandeeq/dev/purpleai/node_modules/rettiwt-api/dist/services/FetcherService.js:5:58)

**Comment by Rishikant181** [comment]
What where the search parameters?

**Comment by Rishikant181** [comment]
Working on it, expect patch on monday.

**Comment by Rishikant181** [comment]
@jsonkcli Can you specify all the parameters that you used for searching which thew this error?

**Comment by jsonkcli** [comment]
@Rishikant181 I was just taking a proper look at the API, did you update the search method?

My initial params

 const favUserTweets = await twitter.tweet.search({
      fromUsers: [favUser.userName],
      sinceId: mostRecentTweet?.tweetId || undefined 
      endDate: oneDayFromNow
      links: true
    });

**Comment by jsonkcli** [comment]
It occurs when it get's to next cursor 


 next: Cursor {
    value: 'DAADDAABCgABF7c_Ql1W8VUKAAIXtJprLBqxXQAIAAIAAAACCAADAAAAAAgABAAAAAAKAAUXt6_WVgAnEAoABhe3r9ZV_9jwAAA'
  }

**Comment by Rishikant181** [comment]
Still not able to reproduce the error, unfortunately.

> const favUserTweets = await twitter.tweet.search({
fromUsers: [favUser.userName],
sinceId: mostRecentTweet?.tweetId || undefined
endDate: oneDayFromNow
links: true
});

I need the exact values of these params when the error occurs.

Anothet thing to note: Are you on the latest version of Rettiwt-API?
