### ISSUE TITLE
API_KEY generation issue

### ISSUE THREAD

**Issue by Skydraw** [Rishikant181/Rettiwt-API#456]
Hello,

I have been trying to generate a API_KEY but unfortunetly I get this message when I try it.
I removed my 2FA just in case but it doesn't work either.

Maybe the first "." in email adresse is the problem ?

My input is : 
```rettiwt auth login xxxxx.xxxxx@xxx.xxx @xxxxx xxxxxxxxxxxxxxxxx```

My output : 
```
/usr/local/lib/node_modules/rettiwt-api/node_modules/https-proxy-agent/dist/index.js:54
        this.proxyHeaders = opts?.headers ?? {};
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/rettiwt-api/node_modules/rettiwt-auth/dist/Auth.js:57:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
Thanks you !

**Comment by Rishikant181** [comment]
Are you using a proxy?

**Comment by Skydraw** [comment]
No, But i just found my issue and it was a wrong NodeJS version. 

It work perfectly now.

Thank you for your job !

**Comment by Rishikant181** [comment]
Glad you found it useful!
