### ISSUE TITLE
Strange error when using guest auth in my nodejs project. Unknown Error.

### ISSUE THREAD

**Issue by MsVoxxie** [Rishikant181/Rettiwt-API#497]
As of earlier today and yesterday I started to properly use this project again and then today at random I appear to be receiving this error.

```
Error: Unknown error
    at ApiError.RettiwtError [as constructor] (/root/projects/VibotServices/Vii/node_modules/rettiwt-api/dist/models/errors/RettiwtError.js:27:28)
    at new ApiError (/root/projects/VibotServices/Vii/node_modules/rettiwt-api/dist/models/errors/ApiError.js:35:28)
    at exports.ErrorService.ErrorService.createApiError (/root/projects/VibotServices/Vii/node_modules/rettiwt-api/dist/services/internal/ErrorService.js:124:16)
    at exports.ErrorService.ErrorService.handleApiError (/root/projects/VibotServices/Vii/node_modules/rettiwt-api/dist/services/internal/ErrorService.js:85:20)
    at exports.ErrorService.ErrorService.handle (/root/projects/VibotServices/Vii/node_modules/rettiwt-api/dist/services/internal/ErrorService.js:38:14)
    at /root/projects/VibotServices/Vii/node_modules/rettiwt-api/dist/services/internal/FetcherService.js:187:52
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Any assistance or insight is appreciated :)

**Comment by MsVoxxie** [comment]
Apparently I had a funky bit of unchecked text in my method.

**Comment by MsVoxxie** [comment]
After some testing, it seems the package simply fails to authenticate after some time of being online. Im unsure as to how to resolve this on me own, so re-opening the issue :)

**Comment by Rishikant181** [comment]
So all requests work for some time after the deployment, but after some time, the authentication fails?

**Comment by MsVoxxie** [comment]
It appears that way! The only way I can find to have it function again is to restart my application.

**Comment by Rishikant181** [comment]
Did you try using a proxy just for authentication and not the global proxy (i.e, via `authProxyUrl` and not `proxyUrl`) as described [here](https://github.com/Rishikant181/Rettiwt-API/tree/release?tab=readme-ov-file#cloud-environment)?

**Comment by MsVoxxie** [comment]
My project is not in a cloud envrionment and im not entirely certain what where or how id go about adding a proxy for something that I use on my local network, But to answer your question, no I have not

**Comment by Rishikant181** [comment]
> the package simply fails to authenticate after some time of being online

I misunderstood 'being online' with 'being deployed to cloud' :P

What do you mean by 'going online'?

**Comment by MsVoxxie** [comment]
Ah, after some time of the app running is what I meant

**Comment by Rishikant181** [comment]
Is the issue reproducible or does it seem to happen at random?
