### ISSUE TITLE
Broken tweet list

### ISSUE THREAD

**Issue by gratatouilley** [Rishikant181/Rettiwt-API#546]
Hi,

I'm new to this package and tried TweetService (list)

```js
const fetchAllTweets = (id: string) => {
  rettiwt.tweet
    .list(id)
    .then((data) => console.log(data))
    .catch((err) => console.log(err));
}
```

And received error:
```
TypeError: Cannot read properties of undefined (reading 'value')
    at new CursoredData (/Documents/github/tweet-watcher/node_modules/rettiwt-api/src/models/data/CursoredData.ts:35:84)
    at Object.LIST_TWEETS (/Documents/github/tweet-watcher/node_modules/rettiwt-api/src/collections/Extractors.ts:40:3)
    at TweetService.<anonymous> (/Documents/github/tweet-watcher/node_modules/rettiwt-api/src/services/public/TweetService.ts:201:36)
    at step (/Documents/github/tweet-watcher/node_modules/rettiwt-api/dist/services/public/TweetService.js:59:23)
    at Object.next (/Documents/github/tweet-watcher/node_modules/rettiwt-api/dist/services/public/TweetService.js:40:53)
    at fulfilled (/Documents/github/tweet-watcher/node_modules/rettiwt-api/dist/services/public/TweetService.js:31:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Is this a known issues or any solution for this?

Looking forward for the answer xoxo^^

**Comment by Rishikant181** [comment]
This is not intended behavior. Can you try this with logging on and post the logs?

**Comment by gratatouilley** [comment]
Here is the logging

Code:
```ts
const fetchAllTweets = (id: string) => {
  rettiwt.tweet
    .list(id, 100)
    .then((data) => console.log(data))
    .catch((err) => console.log(err));
}
```

![Screenshot 2024-05-28 at 13 02 42](https://github.com/Rishikant181/Rettiwt-API/assets/23229519/c5909993-a76f-4b6c-9552-6671d8af789b)

**Comment by Rishikant181** [comment]
![image](https://github.com/Rishikant181/Rettiwt-API/assets/66668688/97221222-0bd6-4251-9bcb-88c88080afba)

It seems that tweet list doesn't exist.

**Comment by gratatouilley** [comment]
My bad, I just realized that the function is referring to _Twitter List_. I used to use the function for retrieve user's tweet lists.

Appreciated for the super quick response. Have a nice day!!^^

**Comment by Rishikant181** [comment]
Thanks for the feedback tho, I noticed another legit bug where a cursor error thrown when the given tweet list is invalid :P
