### ISSUE TITLE
Fetching tweet's details suddenly failing randomly with 404 (`NOT_FOUND`)

### ISSUE THREAD

**Issue by Jeto143** [Rishikant181/Rettiwt-API#552]
I have a bot running that suddenly started throwing `NOT_FOUND` errors when fetching tweets a few hours ago. After investigating for a bit, it seems completely random, although it appears to fail way more often than it succeeds.

It might be due to the Twitter API being (somewhat) down (can't find anything online about it), but just in case, here's a way to test it by attempting to fetch [the same tweet](https://twitter.com/AFP/status/1802350417478664517) indefinitely (waiting 5 seconds between attempts).

```js
#!/usr/bin/env node

import { Rettiwt } from 'rettiwt-api';

const r = new Rettiwt({ logging: true });

while (true) {
  await r.tweet.details('1802350417478664517');
  await new Promise(resolve => setTimeout(resolve, 5000));
}
```

And here's the error:

```
RettiwtError: NOT_FOUND
    at HttpError.RettiwtError (/home/jeto/dev/projects/seedplantr/vegan-twitter-bot/node_modules/rettiwt-api/src/models/errors/RettiwtError.ts:8:3)
    at HttpError (/home/jeto/dev/projects/seedplantr/vegan-twitter-bot/node_modules/rettiwt-api/src/models/errors/HttpError.ts:17:3)
    at ErrorService.exports.ErrorService.ErrorService.createHttpError (/home/jeto/dev/projects/seedplantr/vegan-twitter-bot/node_modules/rettiwt-api/src/services/internal/ErrorService.ts:41:10)
    at ErrorService.exports.ErrorService.ErrorService.handleHttpError (/home/jeto/dev/projects/seedplantr/vegan-twitter-bot/node_modules/rettiwt-api/src/services/internal/ErrorService.ts:127:14)
    at ErrorService.exports.ErrorService.ErrorService.handle (/home/jeto/dev/projects/seedplantr/vegan-twitter-bot/node_modules/rettiwt-api/src/services/internal/ErrorService.ts:157:8)
    at TweetService.<anonymous> (/home/jeto/dev/projects/seedplantr/vegan-twitter-bot/node_modules/rettiwt-api/src/services/public/FetcherService.ts:205:22)
    at step (/home/jeto/dev/projects/seedplantr/vegan-twitter-bot/node_modules/rettiwt-api/dist/services/public/FetcherService.js:44:23)
    at Object.throw (/home/jeto/dev/projects/seedplantr/vegan-twitter-bot/node_modules/rettiwt-api/dist/services/public/FetcherService.js:25:53)
    at rejected (/home/jeto/dev/projects/seedplantr/vegan-twitter-bot/node_modules/rettiwt-api/dist/services/public/FetcherService.js:17:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
```

Note: this endpoint doesn't require authentication but it fails the same way regardless.

**Comment by Jeto143** [comment]
Looks like it's fixed now (or at least much better). I'll confirm in a few hours just to be sure!

**Comment by Jeto143** [comment]
Yep, looks like it was just a temporary outage on Twitter's side, sorry!

**Comment by Rishikant181** [comment]
Still I'll be taking a look at it in the morning (I do absolutely nothing on Saturday and Sunday :P)

**Comment by Rishikant181** [comment]
It's back again. I think that endpoint used to fetch details of a single tweet is borked. I'm checking what can be done about it.

**Comment by Rishikant181** [comment]
What I found is that the endpoint works as intended from Postman, but when the exact same request is done via NodeJS, it throws not found. Trying to find a workaround.

Edit 1: cURL works, but Axios fails.

Edit 2: Tried a library called node-libcurl to make HTTP request from inside NodeJS using cURL and it works, but axios fails.

**Comment by Jeto143** [comment]
It's responding fine for me right now (with rettiwt-api). 🤔

edit: Keeps happening randomly, though much less often than yesterday. It really seems like it's on Twitter's side.

**Comment by Rishikant181** [comment]
I just checked again, turns out, it's working while not logged in, but fails while logged in.

**Comment by Rishikant181** [comment]
Please update to Rettiwt-API v3.0.2 for the fix and let me know if it's fixed.

**Comment by Rishikant181** [comment]
Let me know if any other endpoint throws a similar error, cause if it does, we might have to change from axios to cURL for making the requests.

**Comment by Jeto143** [comment]
@Rishikant181 I'm getting `NOT_FOUND` immediately using `3.0.2`, whereas it still seems fine with `3.0.1` (bot is offline but it seems stable when I test it locally for a little while). 🤔

(Was [this change](https://github.com/Rishikant181/Rettiwt-API/pull/554/files#diff-fb07f2901b0eb89e14c656e56e18012eec5b752ee14c054325f22642a5ca00a0R28) intended?)

(Edit: ah just saw [this](https://github.com/Rishikant181/Rettiwt-Core/pull/161/files) so that answers my q I guess)

**Comment by Rishikant181** [comment]
The change was intended. What I did was instead of using the `TweetDetailByRestId` endpoint (which is an internal endpoint btw and in no  way can be accessed by the Twitter Web App), I used `TweetDetails` endpoint, which is basically the same endpoint used by the Web App to fetch details of a Tweet, along with some of it replies.

Regarding the `NOT_FOUND` error, I'll have to check it once again then. It seemed to work fine by switching to `replies` endpoint from rettiwt-core.

**Comment by Jeto143** [comment]
@Rishikant181 Actually it seems to work when I'm logged in (the old endpoint didn't require it). I'll try for a longer time and keep you updated.

**Comment by Rishikant181** [comment]
The issue seems to be inherent in NodeJS. I tried running the same code in Bun and it works. Even the same HTTP request config works on other languages like Python, C#, Java, etc. On NodeJS, the workaround is to use node-libcurl, since it doesn't use NodeJS' native fetch library, instead, it uses libcurl library from C.

**Comment by Jeto143** [comment]
I can confirm I'm not getting any error anymore using `3.0.2` (at least not in like 10 hours).

**Comment by Rishikant181** [comment]
Still, I'll be keeping this issue open until I've worked out a permanent solution instead of a workaround.
