### ISSUE TITLE
Getting RettiwtError: NOT_FOUND when trying to get details of tweets that do currently exist

### ISSUE THREAD

**Issue by nancyvuong** [Rishikant181/Rettiwt-API#553]
Hello,

I've been using Rettiwt to get details of specific tweets for a month now by calling: await client.tweet.details(tweetId); 

Recently though, I've been experiencing this error where calling "await client.tweet.details(tweetId);" would throw this error on certain tweets:

RettiwtError: NOT_FOUND
    at HttpError.RettiwtError [as constructor] (/Users/username/Desktop/projectname/node_modules/rettiwt-api/dist/models/errors/RettiwtError.js:27:28)
    at new HttpError (/Users/username/Desktop/projectname/node_modules/rettiwt-api/dist/models/errors/HttpError.js:32:28)
    at exports.ErrorService.ErrorService.createHttpError (/Users/username/Desktop/projectname/node_modules/rettiwt-api/dist/services/internal/ErrorService.js:37:16)
    at exports.ErrorService.ErrorService.handleHttpError (/Users/username/Desktop/projectname/node_modules/rettiwt-api/dist/services/internal/ErrorService.js:112:20)
    at exports.ErrorService.ErrorService.handle (/Users/username/Desktop/projectname/node_modules/rettiwt-api/dist/services/internal/ErrorService.js:138:14)
    at TweetService.<anonymous> (/Users/username/Desktop/projectname/node_modules/rettiwt-api/dist/services/public/FetcherService.js:230:43)
    at step (/Users/username/Desktop/projectname/node_modules/rettiwt-api/dist/services/public/FetcherService.js:44:23)
    at Object.throw (/Users/username/Desktop/projectname/node_modules/rettiwt-api/dist/services/public/FetcherService.js:25:53)
    at rejected (/Users/username/Desktop/projectname/node_modules/rettiwt-api/dist/services/public/FetcherService.js:17:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}

The tweets it would error out on still exist.

Examples include:
-https://twitter.com/Bpm739/status/1761719819555230008
-https://twitter.com/fengnelcake/status/1789543673568612525
-https://twitter.com/oOk__f/status/1795429655845212376

This error doesn't get thrown every tweet I check and I have only started experiencing this about 2 days ago.

**Comment by nancyvuong** [comment]
Whoops looks like this is a duplicate of https://github.com/Rishikant181/Rettiwt-API/issues/552

Will still leave as open for the time being until the problem is confirmed

**Comment by Rishikant181** [comment]
Duplicate of #552

**Comment by Rishikant181** [comment]
Are you using the library as a guest or logged-in user?

**Comment by nancyvuong** [comment]
Logged-in user

**Comment by Rishikant181** [comment]
Okay I have worked out a temporary workaround. That path is on the way.

**Comment by Rishikant181** [comment]
Please update to Rettiwt-API v3.0.2 for the fix and let me know if it's fixed.

The patch requires logging in for getting the details though.

**Comment by nancyvuong** [comment]
Thank you for the fix. I have updated it and it was successful the few times I tried it. I pushed the update to my bot and I will keep monitoring it and get back to you.

**Comment by nancyvuong** [comment]
My bot has been able to fetch tweets without issues with the new update. Thank you so much!
