### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Rishikant181** [Rishikant181/Rettiwt-API#586]
All issues related to logging in will be discussed here.

**Comment by Rishikant181** [comment]
Here is a temporary workaround:

1. Open your browser and go to twitter/X.
2. Open browser developer tools.
3. Navigate to Applications->Cookies (for Chrome) or Storage->Cookies (for Firefox).
4. Copy the values of the 3 fields: `auth_token`, `ct0`, `twid`. Store them temporarily somewhere.
5. Open NodeJS in a terminal and execute the command: `btoa("auth_token=<auth_token_value>;ct0=<ct0_value>;twid=<twid_value>;")`
6. The output  string is your API_KEY.

You only need to do this once to get the API_KEY. The API_KEY should be valid for a year, so no need to do this repeatedly.

**Note**: If you don't want to remain logged into the browser, just follow this process in incognito/private mode of your browser and after generating the API_KEY, just exit incognito/private mode. That way, you won't stay logged in to the browser and at the same time, the API_KEY will remain valid.

**Comment by Rishikant181** [comment]
So I managed to somewhat reproduce the issue. What I did was tried repeated login as well tried to create an account locally, then login to that account using a proxy, which triggered the following response from Twitter while logging in:

```
We blocked an attempt to access your account because we weren't sure it was really you.

This happens when we notice unusual login activity, like an attempt to log in too many times, or from a different location or device.

You'll need to wait before trying to log in again. Some blocks are removed automatically.

Get help with login issues.
```

So, from preliminary examination, it seems that login fails in the following cases:
1. You repeatedly login to an account, while in practice, you should be logging in once, get the API_KEY, then forget about trying it again.
2. You created an account on one system at a specific location, then used a proxy to login to that account using Rettiwt-API, and because of the proxy, the location is different, which triggers the following response.
3. Another possible situation is (not tested), when you create a new burner account, but do not complete the initial actions like following some users, etc, etc.

As it turns out, I am at my wits end. You input highly appreciated in fixing this issue.

**Comment by Rishikant181** [comment]
As a side note, the 'ideal' usage is:
1. Create an account on local system.
2. Complete the full account setup process (don't opt-in for 2FA or anything like that, just the vanilla, basic setup).
3. Login using the CLI or library function to generate API_KEY(s) on the **same system**, if you're logging in as soon as you're creating an account. If you're logging in after some time (days) of creating the account, you may use a different PC or proxy.
4. Save the generated API_KEY for future use. Remember the API_KEY(s) are valid for a year! Do not generate more than one API_KEY repeatedly! For reference, I have been using the same API_KEY for months now.

**Comment by gabrielepinto** [comment]
I followed your instructions to get the api key, but I still get this error when sending the request to get the list of followers of a user:

Error fetching user details: DataValidationError {
  name: 'VALIDATION_ERROR',
  message: 'One or more validation error(s) occured, check details field.',
  details: [ ValidationErrorDetails { field: 'id', constraints: [Array] } ]
}

**Comment by Rishikant181** [comment]
@gabrielepinto The problems is that you are supplying `user.followers` a `username` where it expects a numeric `id` of the user. The `id` is obtained using the `user.details` method, which takes the `username` as input. You can see the same by inspecting the `constraints` field of the line, as follows:

![image](https://github.com/user-attachments/assets/e8cb2488-670c-4f64-bf68-d87b6b432f54)

Any further discussions regarding your issue will take place in a separate issue thread. This thread is reserved for issues while logging in using `rettiwt auth login` method.

**Comment by Elyoussf** [comment]
> Here is a temporary workaround:
> 
>     1. Open your browser and go to twitter/X.
> 
>     2. Open browser developer tools.
> 
>     3. Navigate to Applications->Cookies (for Chrome) or Storage->Cookies (for Firefox).
> 
>     4. Copy the values of the 4 fields: `auth_token`, `ct0`, `kdt`, `twid`. Store them temporarily somewhere.
> 
>     5. Open NodeJS in a terminal and execute the command: `btoa("auth_token=<auth_token_value>;ct0=<ct0_value>;kdt=<kdt_value>;twid=<twid_value>")`
> 
>     6. The output  string is your API_KEY.
> 
> 
> You only need to do this once to get the API_KEY. The API_KEY should be valid for a year, so no need to do this repeatedly.

Bro i did this and it works if the account is still active in the browser if i log out in my browser is not working anymore

**Comment by Rishikant181** [comment]
@Elyoussf You can use incognito/private mode to do the same thing, and after generating API_KEY, just exit incognito/private mode. That way, you will not remain logged in to the browser, at the same time, the API_KEY will remain valid since you never "logged out".

**Comment by improwise** [comment]
Login via CLI does not seem to work, only return empty JSON 

{}

Usage like rettiwt auth login test@test.com test test 

(tried both with and without " around the string values and of course used real values)

**Comment by Rishikant181** [comment]
@improwise Twitter/X's suspicious login measures might have been triggered. This usually happens when you try to login from a seemingly different location by using methods such as VPN, proxy, cloud services, etc. To confirm, can you check the associated email to see if you have received in email from Twitter/X related to a suspicious login or any login code?

**Comment by improwise** [comment]
> @improwise Twitter/X's suspicious login measures might have been triggered. This usually happens when you try to login from a seemingly different location by using methods such as VPN, proxy, cloud services, etc. To confirm, can you check the associated email to see if you have received in email from Twitter/X related to a suspicious login or any login code?

Thanks for responding and for providing this repo. 

I worked find to login in browser(s) even though I was eventually locked out after trying the rettiwt auth login to many times so it seems it was communicating as it should with something at the other end. Is the command supposed to be with " for the values or not? 

I noticed that when I tried without ", it complained about the last characters in my password (which is quite complex), could there be an issue with password length or some special characters? When using the command with the "", it got no error, just the empty response. 

BTW, noticed that in the readme there was both "rettiwt auth login" and "rettiwt-auth login" with a dash, not sure if that is a typo.

**Comment by Rishikant181** [comment]
@improwise 

> Is the command supposed to be with " for the values or not?

Yes, to avoid the following problem:
> it complained about the last characters in my password

Since, some characters might convey special meaning to the shell when not enclosed inside quotes.

> BTW, noticed that in the readme there was both "rettiwt auth login" and "rettiwt-auth login" with a dash, not sure if that is a typo.

It's a typo, will fix it tomorrow.

As for the issue, the CLI login works best when you use it from a local machine. In my case, I usually use Twitter/X from my PC and when I use the CLI to login from the same PC, I never faced an issue, except ofcourse when I tried logging in repeatedly 3 times or more in a row (for testing purpose), in which case, it triggers the suspicious activity measures. After some time, trying again from the CLI works.

Does the browser workaround work for you?

**Comment by Rishikant181** [comment]
@improwise Another thing I notices is that, if you login to Twitter/X from the browser using you email first, followed by the password, the CLI command that usually works is: `rettiwt auth login "<email>" "<username>" "<password>"`

If, however, you use your username to login from the browser, the CLI command that usually works is: `rettiwt auth login "<username>" "<email>" "<password>"`

In short, email and username can be interchanged, depending on which one you use to login to Twitter/X from the browser.

**Comment by improwise** [comment]
> @improwise Another thing I notices is that, if you login to Twitter/X from the browser using you email first, followed by the password, the CLI command that usually works is: `rettiwt auth login "<email>" "<username>" "<password>"`
> 
> If, however, you use your username to login from the browser, the CLI command that usually works is: `rettiwt auth login "<username>" "<email>" "<password>"`
> 
> In short, email and username can be interchanged, depending on which one you use to login to Twitter/X from the browser.

Hi,

So, I debugged the traffic to the Twitter API https://api.twitter.com/1.1/onboarding/task.json and it is basically telling me that the call is suspicious and have been blocked. They are still returning status 200 so that is why it does not get picked up by the error handing. 

In detail, it seems like the request with 

`"subtask_id": "LoginEnterUserIdentifierSSO"`

is getting a response with

`"subtask_id": "DenyLoginSubtask"`

Not sure if it matters but I see that the user agent is 

`User-Agent: axios/1.6.3`

Maybe that gives it away?

**Comment by Rishikant181** [comment]
@improwise Are you using a VPN, Proxy or a Cloud Deployement?

**Comment by improwise** [comment]
@Rishikant181 VPN, but that works when logging into X with a browser running on the same computer.

**Comment by Rishikant181** [comment]
@improwise VPN might be the issue. Try logging in without VPN.

**Comment by improwise** [comment]
@Rishikant181 I just tried the "cookie hack" to get an API key and that seemed to work and also running authenticated calls using it.

**Comment by Rishikant181** [comment]
@improwise The "cookie hack" always works. Authentication using CLI has been wonky since it's tries so hard to mimic the login process. I have an alternate method in mind, which might become the primary method if it seems viable.

**Comment by improwise** [comment]
@Rishikant181 Again, thanks for all the hard work you have put in and is putting into this.

**Comment by Rishikant181** [comment]
You can now use you browser (Chromium-based browser only) to generate the API_KEY using [this](https://chromewebstore.google.com/detail/x-auth-helper/igpkhkjmpdecacocghpgkghdcmcmpfhp) extension, which can help getting the API_KEY, and it always works:

1. Install the aforementioned extension.
2. Login to Twitter/X. If already logged in, skip this step.
3. Click on the extension and then click on `Get Key`. The API_KEY will be generated.
4. Click on `Copy key` or manually copy the generated API_KEY, and store it somewhere secure for later use.

**Note**: The API_KEY will be valid as long as you do not log out from the browser. If you want the API_KEY to be valid for a year, just use incognito mode to repeat the above steps and remember to not log out, but just exit incognito mode. That way, your browser session will be closed and you will not stay logged in (since it was incognito mode), while the API_KEY will be still valid (since you never really "logged out").

As for Firefox users, the extension will soon be ported.

**Comment by Rishikant181** [comment]
Browser-based authentication method has been finalized. Please refer to the [README](https://github.com/Rishikant181/Rettiwt-API?tab=readme-ov-file#1-using-a-browser-recommended) for the how-to.

P.S: Both Chrome and Firefox , as well as their derivatives, are supported.

**Comment by bircher044** [comment]
Hi, im having an issue with the package. I would appreciate if someone could help.
Receiving "{}" responce when trying to generate cookies for authorization (apikey) using cli. Also I got this error when using it as a package for my project: "Failed to authenticate using the given account Credentials".

Im not using vpn, it's my personal local account and I have no issues with login in the browser.

@Rishikant181

**Comment by Rishikant181** [comment]
Is it possible for you to use the browser extensions as an alternative login method?

**Comment by bircher044** [comment]
> Is it possible for you to use the browser extensions as an alternative login method?

unfortunately It's not a solution for me since I need too many accounts.

**Comment by Rishikant181** [comment]
@bircher044 This usually happens when Twitter/X notices the unusual login activity to the account, and most of the times, it's a hit and miss. Can you confirm if you are receiving any form of email from Twitter/X regarding login to the given account(s)?

**Comment by bircher044** [comment]
@Rishikant181 im only receiving "We noticed a login to your account" when i login from the browser. Nothing related not confirmation code or anything like that.

when im trying to auth using package, im getting a problem on 5th subtask ELoginSubtasks.ACCOUNT_DUPLICATION_CHECK. All subtasks before have **status: 'success',**.
![image](https://github.com/user-attachments/assets/d3e22d1f-9876-4a90-9987-78c017d5c196)

I also tried to login via browser and track my network. So I see only first 4 subtasks. At the same time when i remove that 5th task from your package, i managed to receive this cookies but they are weird (**without authToken**).

Response 

```
AuthCredential {
  authToken: 'AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4pu************************************CpTnA',
  guestToken: '18346**********33871854',
  cookies: 'guest_id_marketing=v1%3A***********961362; Max-Age=63072000; Expires=Sun, 13 Sep 2026 15:12:20 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None;guest_id_ads=v1%3A1726***********1362; Max-Age=63072000; Expires=Sun, 13 Sep 2026 15:12:20 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None;personalization_id="v1_/UUDPvvnXi+1dZxA++bZIQ=="; Max-Age=63072000; Expires=Sun, 13 Sep 2026 15:12:20 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None;guest_id=v1%3A1726**********8961362; Max-Age=63072000; Expires=Sun, 13 Sep 2026 15:12:20 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None;att=1-3ou0ET***************************kaQVH65wv; Max-Age=86400; Expires=Sat, 14 Sep 2024 15:12:20 GMT; Path=/; Domain=.twitter.com; Secure; HTTPOnly; SameSite=None'
}
```
I replaced some info with "*" just in case.

**Comment by Rishikant181** [comment]
@bircher044 Thanks for the specific internal error info. As I've not been able to reproduce the issue, this provided some insight as to what to look out for. I'll be trying to debug this specific test.

Sorry for the issue. As it stands, trying to reproduce and fix it is all I can do, with no known workarounds (except the browser method).

Thanks for the feedback.

**Comment by Rishikant181** [comment]
@bircher044 On a side note, do you have any proxies that you can test the login with?

**Comment by bircher044** [comment]
@Rishikant181 thank you for supporting this package for such a long term. 

I tried to use a proxy yesterday, both using your package and globally in my IDE. Had the same "{}" problem. I didnt check subtasks but anyway i think the problem was the same.

**Comment by bircher044** [comment]
@Rishikant181 you mentioned you can't replicate the problem on your side. I asked my friends to try and they have the same issue. So it might be related to accounts, not to computer. 
Let me know if I can share you any of my "problem" accounts and you want to check it.

**Comment by Rishikant181** [comment]
If you are able to share it, please do. It will help to at least isolate the cause of the issue.

**Comment by bircher044** [comment]
Sent on the email you mentioned in your profile.

**Comment by Rishikant181** [comment]
@bircher044 I used the account you provided, and got the following output which was probably causing the issue:

```
{
  "flow_token": "g;172648276934174127:-1726482769348:SImbKI0vvlVDSGFSmI1H4sr7:8",
  "status": "success",
  "subtasks": [
    {
      "subtask_id": "LoginAcid",
      "enter_text": {
        "header": {
          "primary_text": { "text": "Check your email", "entities": [] },
          "secondary_text": {
            "text": "In order to protect your account from suspicious activity, we've sent a confirmation code to ma***********@h******.***. Enter it below to sign in.\t",
            "entities": []
          },
          "user": {
            "id": 1724888893626192000,
            "id_str": "1724888893626191872",
            "name": "Kalyn Daniel",
            "screen_name": "DanielKaly49914",
            "location": "Racine",
            "url": null,
            "description": "\"Got the most popular #NFT ever? It all comes down to owning a Casa Dragone Gyrlock portfolio! Invest and seize the market today",
            "protected": false,
            "followers_count": -1,
            "friends_count": -1,
            "listed_count": null,
            "created_at": "Wed Nov 15 20:35:39 +0000 2023",
            "favourites_count": -1,
            "utc_offset": null,
            "time_zone": null,
            "geo_enabled": false,
            "verified": false,
            "statuses_count": -1,
            "lang": null,
            "contributors_enabled": false,
            "is_translator": false,
            "is_translation_enabled": false,
            "profile_background_color": "",
            "profile_background_image_url": null,
            "profile_background_image_url_https": null,
            "profile_background_tile": false,
            "profile_image_url": "http://pbs.twimg.com/profile_images/1726609867035877376/lu8U5hTl_normal.png",
            "profile_image_url_https": "https://pbs.twimg.com/profile_images/1726609867035877376/lu8U5hTl_normal.png",
            "profile_banner_url": "https://pbs.twimg.com/profile_banners/1724888893626191872/1700490851",
            "profile_link_color": "",
            "profile_sidebar_border_color": "",
            "profile_sidebar_fill_color": "",
            "profile_text_color": "",
            "profile_use_background_image": false,
            "default_profile": true,
            "default_profile_image": false,
            "can_media_tag": null,
            "following": null,
            "follow_request_sent": null,
            "notifications": null,
            "muting": null,
            "blocking": null,
            "blocked_by": null,
            "translator_type": "none",
            "withheld_in_countries": [],
            "followed_by": null
          }
        },
        "detail_text": {
          "text": "Why am I being asked for this information?\n\nReport a problem",
          "entities": [
            {
              "from_index": 0,
              "to_index": 42,
              "navigation_link": {
                "link_type": "chromeless_web_link",
                "link_id": "login_issues_link",
                "url": "https://help.twitter.com/managing-your-account/additional-information-request-at-login"
              }
            },
            {
              "from_index": 44,
              "to_index": 60,
              "navigation_link": {
                "link_type": "chromeless_web_link",
                "link_id": "report_problem_link",
                "url": "https://help.twitter.com/forms/account-access/regain-access"
              }
            }
          ]
        },
        "hint_text": "Confirmation code",
        "multiline": false,
        "auto_capitalization_type": "none",
        "auto_correction_enabled": false,
        "keyboard_type": "text",
        "next_link": {
          "link_type": "task",
          "link_id": "next_link",
          "label": "Next"
        }
      },
      "subtask_back_navigation": "cancel_flow"
    }
  ]
}
```

> `"text": "In order to protect your account from suspicious activity, we've sent a confirmation code to ma***********@h******.***. Enter it below to sign in.\t"`

As you can see, it seems that Twitter/X is sending an OTP to the provided email for verifying if it's really you.

**Comment by Rishikant181** [comment]
@bircher044 Good news, I was able to reproduce your issue, in which case it returned just `{}` in response. Another good news is that I've identified the issue. Currently working on fixing it.

**Comment by bircher044** [comment]
> @bircher044 Good news, I was able to reproduce your issue, in which case it returned just `{}` in response. Another good news is that I've identified the issue. Currently working on fixing it.

@Rishikant181 hello! Is it something significant? Can I help you somehow?

**Comment by Rishikant181** [comment]
@bircher044 It's not that significant. Let me explain it concisely: The cookies are usually returned from Twitter/X in the (presumed) last step of authentication. However, sometimes, they are returned in the 2nd last step instead of the last one. That's the case I didn't account for. That's all.

As for fixing it, Rettiwt-Auth is currently a mess and needs some refactoring. I'll be doing both and making the next release. Once I've refactored it, it will become easier to maintain. Thanks for the offer though.

**Comment by percinor** [comment]
if i use chrom extention got api key ,app will  work very well ,but if i try use email name pwd login to got api key ,return an error ,er msg :
 Error: Failed to authenticate using the given account Credentials
    at <anonymous> (/etc/myapp/twigem/node_modules/rettiwt-auth/src/Auth.ts:189:                    12)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:                    5)
any suggestion? thanks

**Comment by quan612** [comment]
happens to me as well 

the old flow to use **email name pwd login** does not work

> if i use chrom extention got api key ,app will work very well ,but if i try use email name pwd login to got api key ,return an error ,er msg : Error: Failed to authenticate using the given account Credentials at (/etc/myapp/twigem/node_modules/rettiwt-auth/src/Auth.ts:189: 12) at process.processTicksAndRejections (node:internal/process/task_queues:105: 5) any suggestion? thanks

**Comment by Rishikant181** [comment]
@percinor @quan612 Yeah the CLI method has been borked for a while now and I find difficult to take the time to fix it. The go-to method is to use the extension (which works 100% of the time), although it's not a programmatic approach.

**Comment by bytes0xcr6** [comment]
After getting the AUTHTOKEN from the Chrome extension in private mode, I still get the authentication error when I deploy and run a microservice on cloud, to get some tweets from some accounts. This error starts to happen after a couple of hours of being running the microservice and making a query for tweets every 15-20 minutes. If I run the microservice locally I don't get any problem.

 Any solution?

```JSON
Error: Failed to authenticate
    at ApiError.RettiwtError (/workspace/node_modules/rettiwt-api/src/models/errors/RettiwtError.ts:8:3)
    at ApiError (/workspace/node_modules/rettiwt-api/src/models/errors/ApiError.ts:17:3)
    at ErrorService.exports.ErrorService.ErrorService.createApiError (/workspace/node_modules/rettiwt-api/src/services/internal/ErrorService.ts:30:10)
    at ErrorService.exports.ErrorService.ErrorService.handleApiError (/workspace/node_modules/rettiwt-api/src/services/internal/ErrorService.ts:116:14)
    at ErrorService.exports.ErrorService.ErrorService.handle (/workspace/node_modules/rettiwt-api/src/services/internal/ErrorService.ts:156:8)
    at TweetService. (/workspace/node_modules/rettiwt-api/src/services/public/FetcherService.ts:206:22)
    at step (/workspace/node_modules/rettiwt-api/dist/services/public/FetcherService.js:44:23)
    at Object.throw (/workspace/node_modules/rettiwt-api/dist/services/public/FetcherService.js:25:53)
    at rejected (/workspace/node_modules/rettiwt-api/dist/services/public/FetcherService.js:17:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Rishikant181** [comment]
@bytes0xcr6 It might be Twitter/X just detecting it to be a scraper. Which platform are you deploying the microservice to?

**Comment by bytes0xcr6** [comment]
@Rishikant181 I am using Digital Ocean. Amy recommendations for hosting the service?

**Comment by Rishikant181** [comment]
@bytes0xcr6 I have deployments on Replit that seem to work for a very long time (rarely have this error). AFAIK, Replit uses GCP behind the scenes, so I think services based on GCP might work.

**Comment by hexadecimal233** [comment]
> After getting the AUTHTOKEN from the Chrome extension in private mode, I still get the authentication error when I deploy and run a microservice on cloud, to get some tweets from some accounts. This error starts to happen after a couple of hours of being running the microservice and making a query for tweets every 15-20 minutes. If I run the microservice locally I don't get any problem.
> 
> Any solution?
> 
> Error: Failed to authenticate
>     at ApiError.RettiwtError (/workspace/node_modules/rettiwt-api/src/models/errors/RettiwtError.ts:8:3)
>     at ApiError (/workspace/node_modules/rettiwt-api/src/models/errors/ApiError.ts:17:3)
>     at ErrorService.exports.ErrorService.ErrorService.createApiError (/workspace/node_modules/rettiwt-api/src/services/internal/ErrorService.ts:30:10)
>     at ErrorService.exports.ErrorService.ErrorService.handleApiError (/workspace/node_modules/rettiwt-api/src/services/internal/ErrorService.ts:116:14)
>     at ErrorService.exports.ErrorService.ErrorService.handle (/workspace/node_modules/rettiwt-api/src/services/internal/ErrorService.ts:156:8)
>     at TweetService. (/workspace/node_modules/rettiwt-api/src/services/public/FetcherService.ts:206:22)
>     at step (/workspace/node_modules/rettiwt-api/dist/services/public/FetcherService.js:44:23)
>     at Object.throw (/workspace/node_modules/rettiwt-api/dist/services/public/FetcherService.js:25:53)
>     at rejected (/workspace/node_modules/rettiwt-api/dist/services/public/FetcherService.js:17:65)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Putting cookies into the apiKey rettwit will fail to parse them. (like everything is set to empty strings)
But using the Extension works fine for me

**Comment by emraherkol** [comment]
@Rishikant181 If the “Request failed with status code 401” message is returned in like, post, etc., does it definitely mean that the apiKey is invalid and needs to be renewed? Does it also return a 401 error when the transaction cannot be performed due to blocking by the other user? How do I know when the apiKey needs to be renewed in the safest way?

**Comment by emraherkol** [comment]
@Rishikant181 My API keys expire after one week. Are you planning to add a login feature in the future? 😟

**Comment by Rishikant181** [comment]
@emraherkol I want to add it but it's just to complicated and flaky that it constantly breaks. Not to mention the bot challenges while logging in, which prevent it's automation.

**Comment by emraherkol** [comment]
**OBTAINING AN API KEY FROM YOUR PHONE**

I have accounts that need to be active 24 hours a day. When I'm away from my computer, it was very difficult to renew the API key remotely. Today I found a perfect solution. We can install the X Auth Helper extension on the “Orion Browser by Kagi” application. This way, we can easily obtain the API Key from our phone. I wanted to share this with the Rettiwt-API Community here. 🤍

**Comment by HamiguaLu** [comment]
Hi
First of all, thanks for such a great project

I am new to this ,  when i tried today,  can not loging:


```
const API_KEY = 'a2R0PWRJakhYMWhVQlNqc3BSMnBmcmxuaEs4TW9xcldsY1VsdHF5Zm9GYUE7YXV0aF90b2tlbj0wZjMwODUyYzljYTc2YzgwMTlmNmE5OTVhMGIyZDNkOTk1MTdiYTA5O2N0MD1jMjFhMDU1ODUzMDFhZGMyMWRmYzkzZDA2NmQ5OWNlNTNiNjc2OWM3YjgyZjU2OWMxZTI0NmVkNmRkY2M2MTE2Njc1Y2MyY2Q2ZTFjYjgwMjEzN2JlNzg3ZmRkOTMxOGRlNDE5ZDY1OGQ3OTA3ZmY4MmJiMjE1ZGViNjZiYWEzNWExMTE0ZjQ0MzUwYmM0MTljYWU3NmU1M2U2NmQ5N2FiO3R3aWQ9dSUzRDEzNTY3MTQwNDkyMjQ5NDE1Njk7';

import { Rettiwt } from 'rettiwt-api';


const rettiwt = new Rettiwt({ apiKey: API_KEY });

async function userDetails() {
	try {
		const user = await rettiwt.user.details();
		console.log(user);
	} catch (error) {
		console.error('Error fetching user details:', error);
	}
}

await userDetails();
```

above code give me error:  

```
Error fetching user details: DataValidationError {
  name: 'VALIDATION_ERROR',
  message: 'One or more validation error(s) occured, check details field.',
  details: [ ValidationErrorDetails { field: 'id', constraints: [Array] } ]
}
```


I get api key by x-auth extension,  by the way i also tried the dev tools way, got a different api key and seem invalid
```
D:\proj2022\social.auto\bsky.auto\nitter.crawle\node_modules\rettiwt-api\dist\services\public\AuthService.js:112
            throw new Error(Api_1.EApiErrors.BAD_AUTHENTICATION);
                  ^

Error: Invalid authentication data
```

Maybe my way of calc is wrong?
```
// calc_api_key.js

// Replace these with your actual values:
const auth_token = "0f30852c9ca76c8019f6a995a0b2d3d99517ba09"
const ct0 = "c21a05585301adc21dfc93d066d99ce53b6769c7b82f569c1e246ed6ddcc6116675cc2cd6e1cb802137be787fdd9318de419d658d7907ff82bb215deb66baa35a1114f44350bc419cae76e53e66d97ab";
const kdt = "dIjHX1hUBSjspR2pfrlnhK8MoqrWlcUltqyfoFaA";
const twid = "u%3D1356714049224941569";

// Build the string the way Twitter expects
const raw = `auth_token=${auth_token};ct0=${ct0};kdt=${kdt};twid=${twid}`;

// Convert to Base64
const api_key = Buffer.from(raw).toString("base64");

// Output
console.log("API_KEY:");
console.log(api_key);
```

**Comment by Rishikant181** [comment]
@HamiguaLu There must be a trailing semicolon `;` at the end of raw cookie string, i.e, it must be: 

```
const raw = `auth_token=${auth_token};ct0=${ct0};kdt=${kdt};twid=${twid};`;
```

I see that I had missed specifying that in the instructions provided in this thread. I've corrected that now.

**Comment by HamiguaLu** [comment]
> [@HamiguaLu](https://github.com/HamiguaLu) There must be a trailing semicolon `;` at the end of raw cookie string, i.e, it must be:
> 
> ```
> const raw = `auth_token=${auth_token};ct0=${ct0};kdt=${kdt};twid=${twid};`;
> ```
> 
> I see that I had missed specifying that in the instructions provided in this thread. I've corrected that now.

Thanks,  now i can login,  so in my case the chrome broser ext doesn't work,   
Below code works fine
 `const raw = `auth_token=${auth_token};ct0=${ct0};kdt=${kdt};twid=${twid};`;`


Also in README:  
Below code doesn't work,  
```
rettiwt.user.details().then((res) => {
	console.log(res); // Returns details of the user associated with API_KEY_1
});
```

This is the working one:

```
rettiwt.user.details("PetTales_").then((res) => {
	console.log(res); // Returns details of the user associated with API_KEY_1
});
```
